-- 코드를 작성해주세요
SELECT F.ITEM_ID, F.ITEM_NAME, F.RARITY
FROM ITEM_INFO F
JOIN ITEM_TREE T ON F.ITEM_ID = T.ITEM_ID
WHERE F.ITEM_ID NOT IN (
    SELECT DISTINCT PARENT_ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NOT NULL
)
ORDER BY F.ITEM_ID DESC